"""
MDUMENI — Pest & Disease Database (condensed rebuild)
30 pests + 33 diseases for all 30 Zimbabwean crops.
"""

PESTS = [
  {"id":"PEST_001","common_name":"Fall Armyworm","scientific_name":"Spodoptera frugiperda","type":"insect","affects":["CROP_001","CROP_002","CROP_004"],"symptoms":["Window-pane feeding on young leaves — transparent patches","Ragged holes in leaves with frass (sawdust-like droppings) in whorl","Caterpillars in the whorl — green to dark brown with inverted Y on head","Severe: entire whorl consumed, dead heart visible"],"severity":"critical","economic_threshold":"Treat when more than 30% of plants show active infestation","season_risk":[10,11,12,1,2,3],"scouting_method":"Check 20 plants per hectare. Open whorl, look for frass and caterpillars. Scout early morning.","treatments":[{"type":"chemical","product":"Emamectin benzoate (Proclaim 19 g/L)","rate":"200 mL/ha in 200 L water","timing":"Apply when caterpillars are small. Direct spray into whorl.","notes":"Rotate modes of action to prevent resistance."},{"type":"organic","product":"Bacillus thuringiensis (Bt) (DiPel)","rate":"1 kg/ha","timing":"Apply before caterpillars enter whorl.","notes":"Safe for beneficials. Works on young larvae only."},{"type":"organic","product":"Neem extract (Azadirachtin)","rate":"3–5 L/ha of 0.03% solution","timing":"Apply every 5–7 days at first sign.","notes":"Use as preventative."}],"prevention":["Plant early to avoid peak armyworm flights","Use push-pull — plant Desmodium between rows","Remove crop debris after harvest"]},
  {"id":"PEST_002","common_name":"Maize stalk borer","scientific_name":"Busseola fusca","type":"insect","affects":["CROP_001","CROP_002"],"symptoms":["Dead heart in young plants — central leaf dies","Row of small holes across leaves","Frass visible in leaf axils","Bored stems — hollow when cut"],"severity":"high","economic_threshold":"Treat when more than 15% of plants show dead heart","season_risk":[10,11,12,1,2],"scouting_method":"Check 20 plants per hectare. Examine leaf axils for frass.","treatments":[{"type":"chemical","product":"Carbofuran 5G (Furadan)","rate":"10 kg/ha","timing":"Apply granules into whorl at first sign.","notes":"Wear full PPE. Do not apply near water."},{"type":"organic","product":"Bt (Bacillus thuringiensis var. kurstaki)","rate":"1 kg/ha","timing":"Apply at egg-hatch stage.","notes":"Must contact caterpillar before stem entry."}],"prevention":["Early planting","Crop rotation with legumes","Deep ploughing after harvest"]},
  {"id":"PEST_003","common_name":"Ear worm","scientific_name":"Helicoverpa armigera","type":"insect","affects":["CROP_001","CROP_013","CROP_030"],"symptoms":["Feeding damage in silk channel at cob tip","Caterpillar visible at tip","Frass and webbing at silk entry","Kernel damage and mould"],"severity":"medium","economic_threshold":"Treat during silking if moths are active","season_risk":[12,1,2,3],"scouting_method":"Check 10 silking cobs per hectare. Look for fresh frass at silk entry.","treatments":[{"type":"chemical","product":"Spinosad (Tracer 480 SC)","rate":"120 mL/ha","timing":"Apply at 50% silking. Repeat after 5 days."},{"type":"organic","product":"Mineral oil application to silk","rate":"2–5 mL per cob tip","timing":"Apply 3–7 days after silk emergence.","notes":"Labour-intensive but effective for small plots."}],"prevention":["Uniform-maturity varieties","Encourage natural enemies (Trichogramma wasps)"]},
  {"id":"PEST_004","common_name":"Sorghum shootfly","scientific_name":"Atherigona soccata","type":"insect","affects":["CROP_002"],"symptoms":["Dead heart in young seedlings","Maggot inside dead shoot","Wilted yellowing central leaf that pulls out easily"],"severity":"high","economic_threshold":"Treat when more than 10% of plants show dead heart in first 3 weeks","season_risk":[10,11,12],"scouting_method":"Check 20 plants per hectare in first 3 weeks.","treatments":[{"type":"chemical","product":"Imidacloprid seed treatment (Gaucho 600 FS)","rate":"6 mL per kg seed","timing":"Treat seed before planting.","notes":"Most effective prevention."},{"type":"chemical","product":"Chlorpyrifos (Dursban 48 EC)","rate":"1 L/ha","timing":"Apply at seedling emergence if no seed treatment."}],"prevention":["Early planting","Tolerant varieties","Remove affected plants early"]},
  {"id":"PEST_005","common_name":"Sorghum midge","scientific_name":"Stenodiplosis sorghicola","type":"insect","affects":["CROP_002"],"symptoms":["Orange-red maggots in florets","Shrivelled empty grain","Small orange flies on flowering panicle"],"severity":"high","economic_threshold":"Treat when 1 midge per panicle during flowering","season_risk":[1,2,3],"scouting_method":"Scout 06:00–09:00. Count insects on 20 flowering panicles.","treatments":[{"type":"chemical","product":"Lambda-cyhalothrin (Karate 2.5 WG)","rate":"200 g/ha","timing":"Apply at 50% flowering. Repeat every 5 days."},{"type":"organic","product":"Pyrethrin (Pyrellin EC)","rate":"500 mL/ha","timing":"Apply early morning during flowering."}],"prevention":["Early planting","Midge-tolerant varieties (e.g. SV2)"]},
  {"id":"PEST_006","common_name":"Aphids (cereal)","scientific_name":"Rhopalosiphum maidis","type":"insect","affects":["CROP_003","CROP_005","CROP_001"],"symptoms":["Clusters of small green/yellow insects on leaves","Honeydew on leaves — sooty mould follows","Curled yellowing leaves","Stunted growth"],"severity":"medium","economic_threshold":"Treat when more than 500 aphids per tiller on 20% of plants","season_risk":[5,6,7,8,9],"scouting_method":"Check 20 tillers. Count aphids. Note ladybirds and parasitic wasps.","treatments":[{"type":"chemical","product":"Dimethoate 40% EC","rate":"300 mL/ha","timing":"Apply when threshold reached."},{"type":"organic","product":"Insecticidal soap (potassium soap)","rate":"5 L/ha of 2% solution","timing":"Apply when colonies first appear. Repeat every 5–7 days.","notes":"Must contact aphids directly."}],"prevention":["Encourage natural enemies","Balanced nitrogen — excess promotes aphids"]},
  {"id":"PEST_007","common_name":"Pearl millet thrips","scientific_name":"Frankliniella spp.","type":"insect","affects":["CROP_004"],"symptoms":["Silver streaking on leaves from feeding","Distorted young leaves","Reduced panicle emergence"],"severity":"medium","economic_threshold":"Treat when more than 5 thrips per plant in early growth","season_risk":[10,11,12],"scouting_method":"Tap plant over white paper. Count thrips falling.","treatments":[{"type":"chemical","product":"Spinosad (Tracer)","rate":"100 mL/ha","timing":"Apply at first sign. Repeat after 10 days."},{"type":"organic","product":"Neem oil (0.5%)","rate":"5 L/ha","timing":"Apply weekly."}],"prevention":["Avoid late planting","Resistant varieties"]},
  {"id":"PEST_008","common_name":"Soybean pod borer","scientific_name":"Maruca vitrata","type":"insect","affects":["CROP_006","CROP_009"],"symptoms":["Webbing tying flowers and pods","Small holes in pods with frass","Caterpillar inside pod feeding on seeds","Shrivelled empty pods"],"severity":"high","economic_threshold":"Treat when 5% of flowers or pods are infested","season_risk":[12,1,2],"scouting_method":"Check 10 plants per hectare during flowering and pod fill.","treatments":[{"type":"chemical","product":"Lambda-cyhalothrin + Chlorpyrifos (Dursban Star)","rate":"500 mL/ha","timing":"Apply at 50% flowering. Repeat every 7 days during pod fill."},{"type":"organic","product":"Bt (Bacillus thuringiensis var. kurstaki)","rate":"1.5 kg/ha","timing":"Apply at egg hatch. Repeat every 5 days.","notes":"Most effective on young larvae."}],"prevention":["Early planting","Trap crops (cowpeas) around soybean field"]},
  {"id":"PEST_009","common_name":"Red spider mite","scientific_name":"Tetranychus urticae","type":"mite","affects":["CROP_006","CROP_013","CROP_030","CROP_012"],"symptoms":["Fine webbing on undersides of leaves","Yellow stippling on upper leaf surface","Leaf curl and desiccation","Tiny red or yellow mites on leaf underside with hand lens"],"severity":"high","economic_threshold":"Treat when more than 50% of leaves show stippling","season_risk":[7,8,9,10],"scouting_method":"Check undersides of 20 leaves per hectare with hand lens.","treatments":[{"type":"chemical","product":"Abamectin (Dynamec 18 EC)","rate":"300 mL/ha","timing":"Apply at first sign. Cover leaf undersides thoroughly.","notes":"Rotate with other modes of action."},{"type":"organic","product":"Sulphur (wettable sulphur 80%)","rate":"3 kg/ha","timing":"Apply preventatively in hot, dry conditions.","notes":"Do not apply above 32°C — phytotoxic."}],"prevention":["Avoid dusty conditions","Maintain field borders","Encourage predatory mites"]},
  {"id":"PEST_010","common_name":"Groundnut leaf miner","scientific_name":"Aproaerema modicella","type":"insect","affects":["CROP_007"],"symptoms":["Silvery blotch mines on leaflets","Rolled leaflets tied with silk","Skeletonised leaves in severe infestations"],"severity":"medium","economic_threshold":"Treat when more than 10% of leaflets show active mines","season_risk":[11,12,1,2],"scouting_method":"Check 20 plants per hectare. Examine leaflets for mines and rolling.","treatments":[{"type":"chemical","product":"Profenofos (Curacron 500 EC)","rate":"500 mL/ha","timing":"Apply at first sign of leaf rolling."},{"type":"organic","product":"Neem extract","rate":"5 L/ha","timing":"Apply weekly as preventative."}],"prevention":["Avoid late planting","Remove infested leaves"]},
  {"id":"PEST_011","common_name":"Bean fly","scientific_name":"Ophiomyia phaseoli","type":"insect","affects":["CROP_008","CROP_009"],"symptoms":["Yellow swelling at base of stem (gall)","Maggot tunnelling in stem base","Wilting and death of young seedlings","Stunted weak plants"],"severity":"high","economic_threshold":"Treat when more than 20% of seedlings show swelling or wilting","season_risk":[10,11,12,1],"scouting_method":"Check 20 seedlings per hectare. Look for stem swelling.","treatments":[{"type":"chemical","product":"Imidacloprid seed treatment (Gaucho 600 FS)","rate":"6 mL per kg seed","timing":"Treat seed before planting. Best control."},{"type":"organic","product":"Wood ash applied to soil surface","rate":"500 kg/ha","timing":"Apply at planting.","notes":"Reduces fly landing. Traditional method."}],"prevention":["Seed treatment is most effective","Early planting","High plant density"]},
  {"id":"PEST_012","common_name":"Cowpea weevil","scientific_name":"Callosobruchus maculatus","type":"insect","affects":["CROP_009","CROP_008"],"symptoms":["Round exit holes in stored grain (1–2 mm)","Fine powdery frass inside grain","Shrivelled hollowed seeds","Adult weevils visible in storage"],"severity":"critical","economic_threshold":"Any infestation in storage is economically important","season_risk":[1,2,3,4,5,6,7,8,9,10,11,12],"scouting_method":"Inspect stored grain monthly. Check for exit holes, frass, live adults.","treatments":[{"type":"chemical","product":"Actellic Super dust (Pirimiphos methyl + Permethrin)","rate":"1 g per kg of grain","timing":"Apply at time of storage. Mix thoroughly.","notes":"Follow PHI for food safety."},{"type":"organic","product":"Hermetic storage bags (PICS triple-layer bags)","rate":"N/A — physical control","timing":"Fill bags with dry grain. Seal tightly.","notes":"Oxygen deprivation. No chemicals needed. Grain must be below 12% moisture."}],"prevention":["Dry grain below 12% moisture","Clean storage containers","Store in hermetic bags"]},
  {"id":"PEST_013","common_name":"Cotton bollworm","scientific_name":"Helicoverpa armigera","type":"insect","affects":["CROP_010","CROP_013"],"symptoms":["Holes in squares, flowers, and bolls","Caterpillar at entry hole — green to brown striped","Frass at entry hole","Premature boll drop"],"severity":"critical","economic_threshold":"Treat when more than 5% of bolls are infested","season_risk":[12,1,2,3],"scouting_method":"Check 20 plants at each visit. Examine squares, flowers, and young bolls.","treatments":[{"type":"chemical","product":"Emamectin benzoate (Proclaim)","rate":"200 mL/ha","timing":"Apply at egg hatch using pheromone trap data."},{"type":"organic","product":"NPV (Helicoverpa-specific nucleopolyhedrovirus)","rate":"Per label","timing":"Apply when eggs are hatching.","notes":"Highly specific. Safe for beneficials."}],"prevention":["Pheromone trap monitoring","Destroy crop residues after harvest"]},
  {"id":"PEST_014","common_name":"Cotton aphid / whitefly","scientific_name":"Aphis gossypii / Bemisia tabaci","type":"insect","affects":["CROP_010"],"symptoms":["Sticky honeydew on leaves — sooty mould follows","Yellowing and curling of leaves","White insects flying when disturbed","Aphid colonies on growing points"],"severity":"high","economic_threshold":"Treat whitefly when more than 5 adults per leaf on 50% of plants","season_risk":[11,12,1,2,3],"scouting_method":"Check undersides of 20 leaves. Tap plants to count adult whitefly.","treatments":[{"type":"chemical","product":"Imidacloprid (Confidor 200 SL)","rate":"250 mL/ha","timing":"Apply when threshold reached.","notes":"Systemic — very effective on sucking insects."},{"type":"organic","product":"Insecticidal soap + neem oil mixture","rate":"5 L/ha soap + 2 L/ha neem","timing":"Apply weekly when populations build."}],"prevention":["Reflective mulch deters whitefly","Yellow sticky traps","Avoid excess nitrogen"]},
  {"id":"PEST_015","common_name":"Tobacco aphid","scientific_name":"Myzus persicae","type":"insect","affects":["CROP_011"],"symptoms":["Clusters of green aphids on young leaves","Distorted curled leaves","Virus symptoms from aphid feeding","Sooty mould on honeydew"],"severity":"critical","economic_threshold":"Treat immediately — virus vector. Zero tolerance in seedbeds.","season_risk":[8,9,10,11],"scouting_method":"Check growing points and leaf undersides of 20 plants. Use yellow sticky traps.","treatments":[{"type":"chemical","product":"Pirimicarb (Pirimor 50 DG)","rate":"300 g/ha","timing":"Apply at first sighting. Selective — spares beneficials.","notes":"Excellent for IPM."},{"type":"chemical","product":"Flonicamid (Teppeki 50 WG)","rate":"140 g/ha","timing":"Apply as soon as aphids detected."}],"prevention":["Mineral oil sprays reduce virus transmission","Remove virus-infected plants immediately","Maintain weed-free borders"]},
  {"id":"PEST_016","common_name":"Sunflower head weevil","scientific_name":"Cylindrocopturus adspersus","type":"insect","affects":["CROP_012"],"symptoms":["Small holes drilled into developing seeds","White grubs inside seeds","Premature seed drop"],"severity":"medium","economic_threshold":"Treat when more than 10% of heads show active feeding","season_risk":[1,2,3],"scouting_method":"Check 10 heads per hectare during seed fill.","treatments":[{"type":"chemical","product":"Cypermethrin (Cipkill 200 EC)","rate":"150 mL/ha","timing":"Apply at 50% petal drop when seeds forming."}],"prevention":["Early harvest when seeds physiologically mature"]},
  {"id":"PEST_017","common_name":"Tomato whitefly","scientific_name":"Bemisia tabaci","type":"insect","affects":["CROP_013","CROP_030"],"symptoms":["Tiny white insects flying when plants disturbed","Yellow scale-like nymphs on leaf undersides","Honeydew and sooty mould","Yellowing leaves with irregular mosaic from virus"],"severity":"high","economic_threshold":"Treat when more than 3 adults per leaflet on 50% of plants","season_risk":[6,7,8,9,10,11],"scouting_method":"Tap plants and count flying adults. Check leaf undersides for nymphs.","treatments":[{"type":"chemical","product":"Spirotetramat (Movento 150 OD)","rate":"600 mL/ha","timing":"Apply at first detection. Systemic."},{"type":"organic","product":"Neem oil (0.3% azadirachtin)","rate":"5 L/ha","timing":"Apply weekly. Disrupts nymph development."}],"prevention":["Yellow sticky traps","Reflective mulch","Plant virus-resistant varieties"]},
  {"id":"PEST_018","common_name":"Tomato fruit borer","scientific_name":"Helicoverpa armigera","type":"insect","affects":["CROP_013","CROP_030"],"symptoms":["Entry hole in calyx end of fruit with frass","Caterpillar inside fruit","Rotting fruit from secondary infection"],"severity":"critical","economic_threshold":"Treat at first egg masses or young caterpillars on fruit","season_risk":[11,12,1,2],"scouting_method":"Check 20 plants. Examine fruit for entry holes. Use pheromone traps.","treatments":[{"type":"chemical","product":"Emamectin benzoate (Proclaim 19 g/L)","rate":"200 mL/ha","timing":"Apply at egg-hatch. Repeat every 7 days."},{"type":"organic","product":"NPV (HearNPV)","rate":"Per label","timing":"Apply at egg-hatch.","notes":"Kills young larvae before fruit entry."}],"prevention":["Pheromone traps to time sprays","Remove and destroy fallen infested fruits"]},
  {"id":"PEST_019","common_name":"Onion thrips","scientific_name":"Thrips tabaci","type":"insect","affects":["CROP_014","CROP_029"],"symptoms":["Silver streaking on leaves","Distorted twisted young leaves","Stunted bulb development","Tiny yellow-brown insects in leaf folds"],"severity":"high","economic_threshold":"Treat when more than 25 thrips per plant","season_risk":[4,5,6,7,8],"scouting_method":"Examine 20 plants. Pull apart leaf folds and count thrips.","treatments":[{"type":"chemical","product":"Spinosad (Tracer 480 SC)","rate":"120 mL/ha","timing":"Apply when 25 thrips per plant reached."},{"type":"organic","product":"Kaolin clay (Surround WP)","rate":"25 kg/ha in 500 L water","timing":"Apply preventatively.","notes":"Physical barrier on plant surface."}],"prevention":["Adequate irrigation — thrips love dry conditions","Blue sticky traps","Weed control in borders"]},
  {"id":"PEST_020","common_name":"Diamondback moth","scientific_name":"Plutella xylostella","type":"insect","affects":["CROP_015","CROP_016"],"symptoms":["Window-pane feeding — transparent patches","Small green caterpillars that wriggle violently when touched","Holes through leaves","White cocoons on leaf undersides"],"severity":"critical","economic_threshold":"Treat when more than 2 larvae per plant in seedling stage","season_risk":[1,2,3,4,5,6,7,8,9,10,11,12],"scouting_method":"Check 20 plants. Touch caterpillars — active wriggling confirms DBM.","treatments":[{"type":"chemical","product":"Indoxacarb (Steward 150 SC)","rate":"200 mL/ha","timing":"Apply when larvae are small. Rotate modes of action — DBM develops resistance rapidly."},{"type":"organic","product":"Bt (Bacillus thuringiensis var. kurstaki)","rate":"1 kg/ha","timing":"Apply every 5 days.","notes":"DBM rarely develops Bt resistance. Excellent for IPM."}],"prevention":["Pheromone trap monitoring","Intercrop with tomatoes or celery","Remove residues immediately"]},
  {"id":"PEST_021","common_name":"Cucumber beetle / Aphid on cucurbits","scientific_name":"Diabrotica spp. / Aphis gossypii","type":"insect","affects":["CROP_017","CROP_018","CROP_028"],"symptoms":["Yellow-green aphid colonies on young shoots","Wilting and distortion of growing tips","Beetle feeding holes in leaves and fruit rind","Virus symptoms from aphid transmission"],"severity":"medium","economic_threshold":"Aphids on more than 20% of plants; beetles when more than 2 per plant","season_risk":[10,11,12,1,2],"scouting_method":"Check 20 plants. Examine growing tips and leaf undersides.","treatments":[{"type":"chemical","product":"Imidacloprid (Confidor 200 SL)","rate":"200 mL/ha","timing":"Apply at first detection."},{"type":"organic","product":"Neem oil + insecticidal soap","rate":"3 L/ha neem + 5 L/ha soap","timing":"Apply weekly."}],"prevention":["Yellow sticky traps","Row covers on young plants","Reflective mulch"]},
  {"id":"PEST_022","common_name":"Sweet potato weevil","scientific_name":"Cylas formicarius","type":"insect","affects":["CROP_019"],"symptoms":["Small round exit holes in tubers (2–3 mm)","Pink bitter-tasting flesh around tunnels","Narrow-waisted reddish-black weevil on vines","Wilting vines in heavily infested plants"],"severity":"critical","economic_threshold":"Any infestation in tubers causes complete unmarketability","season_risk":[1,2,3,4,5,6,7,8,9,10,11,12],"scouting_method":"Check 20 plants. Look for weevil adults on vines. Dig sample tubers.","treatments":[{"type":"chemical","product":"Chlorpyrifos soil drench at planting","rate":"500 mL/ha in furrow","timing":"Apply at planting."},{"type":"organic","product":"Pheromone mass trapping (Cylas lures)","rate":"50 traps per hectare","timing":"Install at planting. Replace lures every 4–6 weeks.","notes":"Very effective for suppression."}],"prevention":["Earth up ridges regularly","Use clean weevil-free planting material","Harvest on time"]},
  {"id":"PEST_023","common_name":"Cassava mealybug","scientific_name":"Phenacoccus manihoti","type":"insect","affects":["CROP_020"],"symptoms":["White waxy coating on growing points","Stunted distorted growing tips","Bunchy top appearance","Leaf yellowing and early drop"],"severity":"high","economic_threshold":"Treat when more than 50% of growing points are infested","season_risk":[5,6,7,8,9],"scouting_method":"Check 20 growing points. Look for white waxy deposits.","treatments":[{"type":"organic","product":"Epidinocarsis lopezi (biocontrol wasp)","rate":"Mass release — contact extension","timing":"Release at first colony formation.","notes":"Classical biocontrol. Very effective."},{"type":"chemical","product":"Spirotetramat (Movento 150 OD)","rate":"500 mL/ha","timing":"Apply when colonies establishing."}],"prevention":["Certified clean planting material","Quarantine new material"]},
  {"id":"PEST_024","common_name":"Potato tuber moth","scientific_name":"Phthorimaea operculella","type":"insect","affects":["CROP_021"],"symptoms":["Serpentine mines in leaves","Caterpillars tunnelling in tubers in field and storage","Webbing and frass on stored tubers"],"severity":"critical","economic_threshold":"Any infestation in storage. In field: 10% leaf mining","season_risk":[1,2,3,4,5,6,7,8,9],"scouting_method":"Inspect stored tubers weekly. In field, check leaves for mines.","treatments":[{"type":"chemical","product":"Chlorpyrifos (Dursban 48 EC)","rate":"500 mL/ha","timing":"Apply when leaf mines appear. Cover soil surface."},{"type":"organic","product":"Bt powder mixed with dry sand in storage","rate":"Thin layer over tubers","timing":"Apply at storage."}],"prevention":["Hill up soil to cover tubers","Harvest promptly","Store in cool dark sealed conditions"]},
  {"id":"PEST_025","common_name":"Papaya mealybug","scientific_name":"Paracoccus marginatus","type":"insect","affects":["CROP_022"],"symptoms":["White cottony masses on stems, leaves and fruit","Yellowing and distortion of young leaves","Fruit blemishes"],"severity":"high","economic_threshold":"Treat when visible colonies on more than 20% of plants","season_risk":[5,6,7,8,9,10],"scouting_method":"Inspect growing points, fruit clusters and leaf undersides of 20 plants.","treatments":[{"type":"chemical","product":"Imidacloprid soil drench","rate":"1 g a.i. per tree","timing":"Apply at first sign."},{"type":"organic","product":"Neem oil (1%)","rate":"5 L/ha","timing":"Apply weekly."}],"prevention":["Avoid excessive nitrogen","Introduce Acerophagus papayae parasitic wasp"]},
  {"id":"PEST_026","common_name":"Mango seed weevil","scientific_name":"Sternochetus mangiferae","type":"insect","affects":["CROP_023"],"symptoms":["No external symptoms","Grub in seed — found at cutting","Premature fruit drop"],"severity":"medium","economic_threshold":"Monitor for export market compliance — quarantine pest","season_risk":[10,11,12,1,2],"scouting_method":"Cut fallen fruit and inspect seed.","treatments":[{"type":"chemical","product":"Dimethoate (Rogor 40 EC)","rate":"300 mL/100 L water","timing":"Apply at petal fall and fruit set."}],"prevention":["Collect and destroy fallen fruit","Hot-water treatment of fruit for export"]},
  {"id":"PEST_027","common_name":"Avocado mite complex","scientific_name":"Oligonychus perseae","type":"mite","affects":["CROP_024"],"symptoms":["Brown necrotic patches on upper leaf surface","Fine webbing on leaf undersides","Early leaf drop"],"severity":"medium","economic_threshold":"Treat when more than 20% leaf area shows necrosis","season_risk":[7,8,9,10],"scouting_method":"Check leaf undersides of 20 leaves with hand lens.","treatments":[{"type":"chemical","product":"Hexythiazox (Nissorun 10 WP)","rate":"400 g/ha","timing":"Apply at first sign of colony formation."}],"prevention":["Adequate irrigation","Avoid overhead irrigation"]},
  {"id":"PEST_028","common_name":"Banana weevil","scientific_name":"Cosmopolites sordidus","type":"insect","affects":["CROP_025"],"symptoms":["Tunnels in the corm","Yellowing and toppling of plants","White grubs in corm when cut","Stunted sucker production"],"severity":"critical","economic_threshold":"More than 5 weevils per corm trap per week","season_risk":[1,2,3,4,5,6,7,8,9,10,11,12],"scouting_method":"Use split pseudostem traps. Count weevils every 2 weeks.","treatments":[{"type":"chemical","product":"Chlorpyrifos (Dursban 48 EC) soil application","rate":"5 mL per planting hole","timing":"Apply at planting and 6-month intervals."},{"type":"organic","product":"Beauveria bassiana","rate":"5e13 spores/ha","timing":"Apply as soil drench around corm.","notes":"Biological control. Best in cool, moist conditions."}],"prevention":["Certified disease-free planting material","Remove old pseudostems promptly"]},
  {"id":"PEST_029","common_name":"Sugarcane borer","scientific_name":"Eldana saccharina","type":"insect","affects":["CROP_026"],"symptoms":["Dead heart in young ratoons","Bored internodes — hollow when cut","Frass at entry point","Reduced sugar content"],"severity":"critical","economic_threshold":"Treat when more than 10% of stalks show boring damage","season_risk":[10,11,12,1,2],"scouting_method":"Check 50 random stalks per hectare. Cut open suspect stalks.","treatments":[{"type":"chemical","product":"Chlorpyrifos (Dursban 48 EC) stalk application","rate":"1 L/ha","timing":"Apply when moths are active."},{"type":"organic","product":"Cotesia flavipes (parasitic wasp) mass release","rate":"10,000 wasps per hectare","timing":"Release at egg-hatch period.","notes":"Classical biocontrol used in commercial cane."}],"prevention":["Harvest ratoons on time","Burn or shred trash after harvest"]},
  {"id":"PEST_030","common_name":"Sesame gall midge","scientific_name":"Asphondylia sesami","type":"insect","affects":["CROP_027"],"symptoms":["Galled (swollen) seed capsules","Premature capsule drop","Distorted stem tips"],"severity":"medium","economic_threshold":"Treat when more than 15% of capsules are galled","season_risk":[12,1,2],"scouting_method":"Check 20 plants. Examine developing capsules for swelling.","treatments":[{"type":"chemical","product":"Dimethoate 40% EC","rate":"250 mL/ha","timing":"Apply at flowering when midges laying eggs."}],"prevention":["Early planting","Destroy crop residues"]},

  {"id":"PEST_031","common_name":"Grain weevil (storage)","scientific_name":"Sitophilus granarius","type":"insect",
   "affects":["CROP_031","CROP_001","CROP_002","CROP_004"],
   "symptoms":["Round exit holes in stored grain","Fine flour-like dust in bags","Grain hollowed out inside","Musty smell in storage"],"severity":"high","economic_threshold":"Any infestation — treat immediately","season_risk":[1,2,3,4,5,6,7,8,9,10,11,12],
   "scouting_method":"Sieve grain sample — look for live weevils and exit holes. Probe for hotspots.",
   "treatments":[{"type":"chemical","product":"Actellic 50 EC (Pirimiphos-methyl)","rate":"20 mL per tonne","timing":"At storage — mix through grain before bagging."},{"type":"organic","product":"Diatomaceous earth","rate":"1 kg per 100 kg grain","timing":"Mix through dry grain at storage."}],
   "prevention":["Dry grain below 12% moisture","Use hermetic PICS bags","Clean storage before use","Store bags on wooden pallets"]},

  {"id":"PEST_032","common_name":"Aphids on vegetables","scientific_name":"Myzus persicae / Aphis gossypii","type":"insect",
   "affects":["CROP_037","CROP_038","CROP_039","CROP_040","CROP_041","CROP_042","CROP_043","CROP_044","CROP_045","CROP_053","CROP_058","CROP_060"],
   "symptoms":["Colonies on leaf undersides","Yellowing and curling of young leaves","Sticky honeydew — sooty mould follows","Stunted plants and distorted growing tips"],"severity":"medium","economic_threshold":"Treat when >20% of plants show aphid colonies","season_risk":[5,6,7,8,9,10],
   "scouting_method":"Check leaf undersides and growing tips weekly. Yellow sticky traps show early arrival.",
   "treatments":[{"type":"chemical","product":"Imidacloprid (Confidor 200 SL)","rate":"150 mL/ha","timing":"At first colony detection. Not on open flowers."},{"type":"organic","product":"Neem extract (Azadirachtin 0.03%)","rate":"3–5 L/ha","timing":"Every 5–7 days. Spray undersides."},{"type":"organic","product":"Insecticidal soap","rate":"5 mL/L water","timing":"Direct spray on colonies."}],
   "prevention":["Introduce ladybirds and lacewings","Avoid excess nitrogen","Yellow sticky trap monitoring"]},

  {"id":"PEST_033","common_name":"Leaf miner","scientific_name":"Liriomyza trifolii","type":"insect",
   "affects":["CROP_037","CROP_038","CROP_044","CROP_013","CROP_041","CROP_042"],
   "symptoms":["White winding tunnels (mines) on leaf surface","Tiny maggots inside mines","Yellow stippling from female feeding punctures","Premature leaf drop in severe cases"],"severity":"medium","economic_threshold":"Treat when mines on >15% of leaves","season_risk":[5,6,7,8,9,10],
   "scouting_method":"Hold leaf to light — mines appear as white channels. Count affected leaves per 10 sampled.",
   "treatments":[{"type":"chemical","product":"Cyromazine (Trigard 75 WP)","rate":"200 g/ha","timing":"At first mine detection."},{"type":"organic","product":"Spinosad (Tracer)","rate":"120 mL/ha","timing":"Evening application — safe for beneficials."}],
   "prevention":["Destroy crop debris immediately","Yellow sticky traps","Avoid excess nitrogen"]},

  {"id":"PEST_034","common_name":"Fruit fly","scientific_name":"Ceratitis capitata / C. rosa","type":"insect",
   "affects":["CROP_046","CROP_047","CROP_048","CROP_049","CROP_022","CROP_023"],
   "symptoms":["Sting punctures on fruit skin","Premature fruit drop","Maggots inside ripe fruit","Rotting from inside without obvious external damage"],"severity":"critical","economic_threshold":"Any fruit sting is commercial loss","season_risk":[11,12,1,2,3,4],
   "scouting_method":"Hang food-based lure traps in canopy — one per 4 trees. Count weekly. Check fallen fruit for maggots.",
   "treatments":[{"type":"chemical","product":"Protein bait spray (GF-120 or Malathion + protein)","rate":"Spot spray 1 in 10 trees, rotating","timing":"Begin at fruit colouring. Repeat weekly."},{"type":"organic","product":"Exclusion netting over fruit clusters","rate":"Full coverage","timing":"From fruit set to harvest."}],
   "prevention":["Collect and destroy fallen fruit daily","Remove overripe fruit from tree","Destroy crop debris after harvest"]},

  {"id":"PEST_035","common_name":"Coffee berry borer","scientific_name":"Hypothenemus hampei","type":"insect",
   "affects":["CROP_050"],
   "symptoms":["Tiny bore hole at blossom end of berry","Berry shrivels or drops early","Grubs and frass inside berry","Significant yield loss in infested blocks"],"severity":"critical","economic_threshold":"Economic impact at 2–3% berry infestation","season_risk":[11,12,1,2,3,4],
   "scouting_method":"Sample 100 berries per block. Dissect for bore holes. Use BROCAP traps baited with alcohol.",
   "treatments":[{"type":"chemical","product":"Chlorpyrifos","rate":"Per label","timing":"At first bore detection."},{"type":"organic","product":"Beauveria bassiana (Bb)","rate":"3 kg/ha","timing":"Apply in humid conditions. Evening application."}],
   "prevention":["Strip all berries at harvest — leave none on tree or ground","Release Phymastichus coffea parasitic wasp"]},

  {"id":"PEST_036","common_name":"Tea mosquito bug","scientific_name":"Helopeltis spp.","type":"insect",
   "affects":["CROP_052","CROP_051","CROP_050"],
   "symptoms":["Brown necrotic spots on young shoots","Shoot die-back — flush destroyed","Canker-like lesions on stems","Flower and fruit damage"],"severity":"high","economic_threshold":"Treat when average 5 bugs per 100 shoots","season_risk":[10,11,12,1,2,3],
   "scouting_method":"Shake shoots over white tray — count falling bugs. Inspect young flush for necrotic spots.",
   "treatments":[{"type":"chemical","product":"Imidacloprid (Confidor)","rate":"Per label","timing":"At flush when populations exceed threshold."},{"type":"organic","product":"Neem oil spray","rate":"3 L/ha","timing":"Every 7–10 days at peak periods."}],
   "prevention":["Prune shade trees to reduce humidity","Remove weed hosts","Conserve predatory bugs (Orius spp.)"]}

]

DISEASES = [
  {"id":"DIS_001","common_name":"Northern corn leaf blight","scientific_name":"Exserohilum turcicum","pathogen_type":"fungal","affects":["CROP_001"],"symptoms":["Long cigar-shaped grey-green lesions on lower leaves","Lesions turn tan to brown with irregular margins","Lesions 2.5–15 cm long","Dark sooty spores in humid conditions"],"severity":"high","favourable_conditions":"Cool (18–27°C), high humidity, prolonged leaf wetness.","scouting_method":"Scout from V6 stage. Check lower leaves. Elongated = NCLB.","treatments":[{"type":"chemical","product":"Propiconazole (Tilt 250 EC)","rate":"500 mL/ha","timing":"Apply at VT stage at first observation. Repeat after 14 days."},{"type":"chemical","product":"Azoxystrobin + Propiconazole (Quilt Xcel)","rate":"500 mL/ha","timing":"Apply at tasselling. Most effective as preventative."}],"prevention":["Plant resistant varieties","Crop rotation","Incorporate residues by ploughing"]},
  {"id":"DIS_002","common_name":"Gray leaf spot","scientific_name":"Cercospora zeae-maydis","pathogen_type":"fungal","affects":["CROP_001"],"symptoms":["Rectangular grey-tan lesions bounded by leaf veins","Lesions run parallel to veins giving striped appearance","Premature senescence of lower leaves"],"severity":"high","favourable_conditions":"High humidity, frequent dew, dense canopies.","scouting_method":"Check ear leaf at tasselling as indicator. More than 5% coverage = treat.","treatments":[{"type":"chemical","product":"Azoxystrobin (Amistar 250 SC)","rate":"400 mL/ha","timing":"Apply at tasselling."}],"prevention":["Resistant varieties","Reduce plant density","Crop rotation 2+ years"]},
  {"id":"DIS_003","common_name":"Sorghum ergot","scientific_name":"Claviceps africana","pathogen_type":"fungal","affects":["CROP_002"],"symptoms":["Pink to orange sticky honeydew oozing from florets","White hard fungal bodies replacing grain","Affected grain shrivelled dark and toxic"],"severity":"critical","favourable_conditions":"Cool wet weather during flowering.","scouting_method":"Check panicles during flowering. Look for honeydew droplets — sweet smell.","treatments":[{"type":"chemical","product":"Propiconazole (Tilt 250 EC)","rate":"500 mL/ha","timing":"Apply at 50% flowering. Repeat after 7 days in favourable conditions."}],"prevention":["Early planting","Tolerant varieties","Avoid overhead irrigation during flowering"]},
  {"id":"DIS_004","common_name":"Wheat stem rust","scientific_name":"Puccinia graminis f.sp. tritici","pathogen_type":"fungal","affects":["CROP_003","CROP_005"],"symptoms":["Orange-red pustules on stems and leaves","Pustules break through epidermis — brick-red powder","Lodging in severe cases","Black teliospores on stems at maturity"],"severity":"critical","favourable_conditions":"Warm (15–35°C), high humidity, early morning dew.","scouting_method":"Check 20 plants from tillering. Rub hand on pustule — red powder confirms stem rust.","treatments":[{"type":"chemical","product":"Propiconazole + Tebuconazole (Folicur Plus 400 EC)","rate":"750 mL/ha","timing":"Apply at first pustule. Repeat after 14 days."}],"prevention":["Ug99-resistant varieties","Early planting","Remove volunteer wheat"]},
  {"id":"DIS_005","common_name":"Wheat leaf rust","scientific_name":"Puccinia triticina","pathogen_type":"fungal","affects":["CROP_003"],"symptoms":["Small orange pustules on upper leaf surface","Scattered pustules — not in rows like stem rust","Yellowing around pustules","Heavy infection causes premature leaf death"],"severity":"high","favourable_conditions":"Cool to moderate (10–22°C), high humidity, dew.","scouting_method":"Check upper leaf surface from flag leaf stage.","treatments":[{"type":"chemical","product":"Propiconazole (Tilt 250 EC)","rate":"500 mL/ha","timing":"Apply at flag leaf when disease first seen."}],"prevention":["Resistant varieties","Fungicide seed treatment"]},
  {"id":"DIS_006","common_name":"Pearl millet downy mildew","scientific_name":"Sclerospora graminicola","pathogen_type":"fungal","affects":["CROP_004"],"symptoms":["White downy growth on lower leaf surface","Green islands surrounded by yellowing","Excessive tillering (witches broom)","Sterile panicles — leaf-like structures instead of grain"],"severity":"critical","favourable_conditions":"Wet humid conditions at seedling stage.","scouting_method":"Check seedlings 2–4 weeks for downy growth on leaf undersides.","treatments":[{"type":"chemical","product":"Metalaxyl seed treatment (Apron 35 SD)","rate":"2 g per kg seed","timing":"Treat seed before planting. Most effective strategy."},{"type":"chemical","product":"Metalaxyl (Ridomil Gold 68 WG)","rate":"2.5 kg/ha","timing":"Apply as soil drench at planting if no seed treatment."}],"prevention":["Resistant varieties","Seed treatment essential","Crop rotation — oospores survive 5–8 years","Remove infected plants before spore release"]},
  {"id":"DIS_007","common_name":"Soybean sudden death syndrome","scientific_name":"Fusarium virguliforme","pathogen_type":"fungal","affects":["CROP_006"],"symptoms":["Interveinal chlorosis on upper leaves","Necrosis follows yellowing","Roots rotted with poor nodulation","Defoliation while stems remain standing"],"severity":"high","favourable_conditions":"Cool wet soils at planting. Compacted soils, poor drainage.","scouting_method":"Check root health of symptomatic plants. Pull and wash roots.","treatments":[{"type":"chemical","product":"Fluopyram seed treatment (ILeVO FS)","rate":"Per label","timing":"Apply at planting in high-risk fields."}],"prevention":["Improve drainage","Avoid early planting into cold wet soils","Use tolerant varieties"]},
  {"id":"DIS_008","common_name":"Groundnut late leaf spot","scientific_name":"Cercosporidium personatum","pathogen_type":"fungal","affects":["CROP_007"],"symptoms":["Dark brown to black circular spots on upper leaf surface","Spots have yellow halo","Chlorosis and early defoliation","Similar spots on stems and petioles"],"severity":"high","favourable_conditions":"Humid, high rainfall, 25–30°C. Develops from 30 days after planting.","scouting_method":"Check leaves from 30 days. More than 6 lesions per leaf = treat.","treatments":[{"type":"chemical","product":"Chlorothalonil (Bravo 500 SC)","rate":"1.5 L/ha","timing":"Apply from 30 days every 14 days until pod fill."},{"type":"chemical","product":"Tebuconazole (Folicur 250 EW)","rate":"500 mL/ha","timing":"Apply at first sign. More effective on established infection."}],"prevention":["Crop rotation 2 years","Resistant varieties","Remove crop debris"]},
  {"id":"DIS_009","common_name":"Bean anthracnose","scientific_name":"Colletotrichum lindemuthianum","pathogen_type":"fungal","affects":["CROP_008","CROP_009"],"symptoms":["Dark brown to black sunken lesions on pods","Similar lesions on stems and leaf veins","Pink spore masses in lesion centre in humidity","Seed infection — brown shrunken seeds"],"severity":"high","favourable_conditions":"Cool (13–26°C), wet weather. Seed-borne.","scouting_method":"Check pods and leaves from flowering. Sunken pod lesions are diagnostic.","treatments":[{"type":"chemical","product":"Mancozeb (Dithane M-45)","rate":"2 kg/ha","timing":"Apply from flowering. Repeat every 10–14 days."},{"type":"chemical","product":"Azoxystrobin (Amistar 250 SC)","rate":"400 mL/ha","timing":"Apply at pod set for best protection."}],"prevention":["Certified disease-free seed","Thiram seed treatment","Crop rotation minimum 2 years"]},
  {"id":"DIS_010","common_name":"Cowpea mosaic virus","scientific_name":"Cowpea mosaic virus (CPMV)","pathogen_type":"viral","affects":["CROP_009"],"symptoms":["Mosaic patterning — irregular light and dark green patches","Leaf distortion and blistering","Stunted growth","Reduced pod fill"],"severity":"medium","favourable_conditions":"High aphid populations spread the virus.","scouting_method":"Monitor aphid populations. Check plants for mosaic from emergence.","treatments":[{"type":"cultural","product":"Remove and destroy infected plants","rate":"N/A","timing":"As soon as symptoms appear.","notes":"No chemical cure. Control vector (aphids) to slow spread."}],"prevention":["Control aphid populations","Virus-resistant varieties","Mineral oil sprays reduce aphid transmission","Plant early"]},
  {"id":"DIS_011","common_name":"Cotton boll rot","scientific_name":"Diplodia gossypina / Fusarium spp.","pathogen_type":"fungal","affects":["CROP_010"],"symptoms":["Water-soaked lesions on boll surface","Brown to black discolouration","White or pink mycelium inside boll","Hard non-opening bolls"],"severity":"high","favourable_conditions":"High humidity, prolonged rain during boll fill.","scouting_method":"Check bolls from 60 days. Look for discoloured non-opening bolls.","treatments":[{"type":"chemical","product":"Copper oxychloride (Cuprox WP)","rate":"2 kg/ha","timing":"Apply after rain events during boll fill."}],"prevention":["Control bollworm","Adequate spacing for air circulation"]},
  {"id":"DIS_012","common_name":"Tobacco blue mould","scientific_name":"Peronospora tabacina","pathogen_type":"fungal","affects":["CROP_011"],"symptoms":["Yellow angular spots on upper leaf surface","Blue-grey downy growth on underside of spots","Spots enlarge rapidly in cool wet conditions","Entire leaves can collapse within days"],"severity":"critical","favourable_conditions":"Cool (7–21°C), high humidity, overhead irrigation, crowded seedbeds.","scouting_method":"Scout seedbeds daily in cool wet weather. Disease can destroy seedbed overnight.","treatments":[{"type":"chemical","product":"Metalaxyl + Mancozeb (Ridomil Gold MZ)","rate":"2.5 kg/ha","timing":"Apply at first symptom. Preventatively every 7 days in high risk.","notes":"Use in combination — metalaxyl resistance has developed."},{"type":"chemical","product":"Cymoxanil + Mancozeb (Curzate M8)","rate":"2 kg/ha","timing":"Use as alternative to manage resistance."}],"prevention":["Drip or furrow irrigation in seedbeds","Good seedbed ventilation","Destroy infected seedlings immediately"]},
  {"id":"DIS_013","common_name":"Sunflower downy mildew","scientific_name":"Plasmopara halstedii","pathogen_type":"fungal","affects":["CROP_012"],"symptoms":["Yellowing of upper leaves from seedling stage","White cottony growth on underside","Stunting — infected plants stay small","Premature death in severe cases"],"severity":"high","favourable_conditions":"Cool wet soils at germination. Soil-borne.","scouting_method":"Check seedlings at 2–3 leaf stage for white sporulation on leaf undersides.","treatments":[{"type":"chemical","product":"Metalaxyl seed treatment (Apron 35 SD)","rate":"2.5 g per kg seed","timing":"Treat seed before planting."}],"prevention":["Seed treatment essential","Crop rotation minimum 4 years","Resistant varieties"]},
  {"id":"DIS_014","common_name":"Tomato early blight","scientific_name":"Alternaria solani","pathogen_type":"fungal","affects":["CROP_013","CROP_021"],"symptoms":["Dark brown circular spots with concentric rings (target-board pattern)","Spots begin on older lower leaves","Yellow halo around lesions","Defoliation from bottom upwards"],"severity":"high","favourable_conditions":"Warm (24–29°C), humid weather. Worst after transplanting.","scouting_method":"Check lower leaves from transplanting. Target-board pattern is diagnostic.","treatments":[{"type":"chemical","product":"Chlorothalonil (Bravo 500 SC)","rate":"1.5 L/ha","timing":"Apply from transplanting every 7–10 days when conditions favour disease."},{"type":"chemical","product":"Azoxystrobin + Difenoconazole (Amistar Top 325 SC)","rate":"500 mL/ha","timing":"Apply at first lesion. Curative + protective."},{"type":"organic","product":"Copper hydroxide (Kocide 3000)","rate":"750 g/ha","timing":"Apply every 7 days as preventative."}],"prevention":["Remove infected leaves immediately","Avoid overhead irrigation","Mulch to reduce soil splash","Crop rotation 2 years"]},
  {"id":"DIS_015","common_name":"Tomato late blight","scientific_name":"Phytophthora infestans","pathogen_type":"fungal","affects":["CROP_013","CROP_021"],"symptoms":["Irregular water-soaked patches on leaves — rapidly turn brown","White sporulation on leaf underside in humidity","Brown hard patches on green fruit","Rapid plant collapse in cool wet conditions"],"severity":"critical","favourable_conditions":"Cool (10–25°C), very wet. Can destroy crop in 5–7 days.","scouting_method":"Check leaves daily in cool wet weather. Act immediately — disease spreads explosively.","treatments":[{"type":"chemical","product":"Metalaxyl + Mancozeb (Ridomil Gold MZ 68 WG)","rate":"2.5 kg/ha","timing":"Apply preventatively in high-risk weather every 7 days.","notes":"Most effective tool. Systemic against oomycetes."},{"type":"chemical","product":"Cymoxanil + Mancozeb (Curzate M8)","rate":"2 kg/ha","timing":"Rotate with Ridomil."}],"prevention":["Avoid overhead irrigation","Ensure good air circulation","Remove and destroy infected material","Do not compost infected material"]},
  {"id":"DIS_016","common_name":"Onion purple blotch","scientific_name":"Alternaria porri","pathogen_type":"fungal","affects":["CROP_014"],"symptoms":["Small white lesions with purple centres on leaves","Lesions enlarge — may girdle leaf","Yellowing and death of leaves from tips","Infection of neck during bulb development"],"severity":"high","favourable_conditions":"Warm (25–30°C), humid. Worst in fields with thrips damage.","scouting_method":"Check leaves from 4–5 weeks after transplanting. Purple colouration in lesion is diagnostic.","treatments":[{"type":"chemical","product":"Iprodione (Rovral 500 SC)","rate":"1 L/ha","timing":"Apply from 4 weeks after transplanting every 10–14 days."},{"type":"chemical","product":"Mancozeb (Dithane M-45)","rate":"2 kg/ha","timing":"Apply preventatively in wet conditions."}],"prevention":["Control thrips","Avoid overhead irrigation","Adequate plant spacing"]},
  {"id":"DIS_017","common_name":"Cabbage black rot","scientific_name":"Xanthomonas campestris pv. campestris","pathogen_type":"bacterial","affects":["CROP_015"],"symptoms":["V-shaped yellow lesions starting from leaf margins","Dark veins within lesion visible on underside","Wilting and collapse of infected leaves","Stunted heads or rotted internal tissue"],"severity":"critical","favourable_conditions":"Warm wet weather. Spread by rain splash, contaminated tools. Seed-borne.","scouting_method":"Check leaf margins from transplanting. V-shaped lesion with dark veins is diagnostic.","treatments":[{"type":"chemical","product":"Copper oxychloride (Cuprox WP)","rate":"2 kg/ha","timing":"Apply at transplanting and every 14 days in wet conditions.","notes":"Protective only — no curative chemical."}],"prevention":["Certified disease-free transplants","Hot-water seed treatment (50°C for 25 min)","Crop rotation minimum 2 years","Disinfect tools"]},
  {"id":"DIS_018","common_name":"Downy mildew of brassicas","scientific_name":"Peronospora parasitica","pathogen_type":"fungal","affects":["CROP_016"],"symptoms":["Yellow patches on upper leaf surface","White fluffy growth on underside of yellow patches","Rapidly expanding lesions in cool humid conditions"],"severity":"medium","favourable_conditions":"Cool moist conditions. Worst in seedbeds.","scouting_method":"Check undersides of leaves with yellow patches.","treatments":[{"type":"chemical","product":"Metalaxyl + Mancozeb (Ridomil Gold MZ)","rate":"2.5 kg/ha","timing":"Apply preventatively in cool wet weather."}],"prevention":["Good seedbed ventilation","Avoid overhead irrigation"]},
  {"id":"DIS_019","common_name":"Gummy stem blight","scientific_name":"Didymella bryoniae","pathogen_type":"fungal","affects":["CROP_017"],"symptoms":["Water-soaked lesions on leaves and stems","Amber-coloured gum oozing from stem lesions","Dark fruit rot at blossom end"],"severity":"medium","favourable_conditions":"High humidity, warm temperatures.","scouting_method":"Check stems and fruit from 3 weeks after transplanting. Gum ooze is diagnostic.","treatments":[{"type":"chemical","product":"Thiophanate methyl (Topsin M 70 WP)","rate":"1 kg/ha","timing":"Apply at first sign of stem lesions."}],"prevention":["Crop rotation 2 years","Avoid overhead irrigation","Resistant varieties"]},
  {"id":"DIS_020","common_name":"Powdery mildew of cucurbits","scientific_name":"Sphaerotheca fuliginea","pathogen_type":"fungal","affects":["CROP_018","CROP_028"],"symptoms":["White powdery coating on upper leaf surface","Affected leaves yellow and die","Reduced fruit quality"],"severity":"medium","favourable_conditions":"Dry conditions, low humidity, 20–30°C.","scouting_method":"Check upper leaf surfaces from 3 weeks after transplanting.","treatments":[{"type":"chemical","product":"Wettable sulphur (Thiovit Jet 80 WG)","rate":"3 kg/ha","timing":"Apply at first sign. Effective and low-cost.","notes":"Do not apply above 32°C — phytotoxic."},{"type":"organic","product":"Bicarbonate spray (5 g baking soda + 2 mL soap per 1 L water)","rate":"500 L/ha","timing":"Apply weekly at first sign.","notes":"Raises leaf pH — inhibits spore germination."}],"prevention":["Resistant varieties","Adequate spacing for air circulation"]},
  {"id":"DIS_021","common_name":"Sweet potato virus disease complex","scientific_name":"SPVD (SPCSV + SPFMV)","pathogen_type":"viral","affects":["CROP_019"],"symptoms":["Severe mosaic, chlorosis, and leaf distortion","Stunted vines","Very small deformed tubers","10–90% yield loss"],"severity":"critical","favourable_conditions":"High whitefly populations spread the virus.","scouting_method":"Monitor for whitefly. Check young leaves for mosaic from establishment.","treatments":[{"type":"cultural","product":"Rogue out infected plants","rate":"N/A","timing":"Remove as soon as symptoms appear.","notes":"No chemical cure."}],"prevention":["Virus-tested planting material from certified suppliers","Control whitefly","SPVD-resistant varieties"]},
  {"id":"DIS_022","common_name":"Cassava mosaic disease","scientific_name":"African Cassava Mosaic Virus (ACMV)","pathogen_type":"viral","affects":["CROP_020"],"symptoms":["Yellow-green mosaic on leaves","Leaf distortion and size reduction","Stunted plant growth","Up to 80% yield loss"],"severity":"critical","favourable_conditions":"Spread by whitefly and infected planting material.","scouting_method":"Inspect planting material for mosaic before planting.","treatments":[{"type":"cultural","product":"Remove and destroy infected plants","rate":"N/A","timing":"As soon as symptoms appear."}],"prevention":["Healthy symptom-free stem cuttings","Mosaic-resistant varieties","Control whitefly"]},
  {"id":"DIS_023","common_name":"Potato late blight","scientific_name":"Phytophthora infestans","pathogen_type":"fungal","affects":["CROP_021"],"symptoms":["Dark water-soaked lesions on leaves — rapidly turning brown","White sporulation on lesion underside in humidity","Reddish-brown rot in tubers from skin inward","Rapid collapse in wet conditions"],"severity":"critical","favourable_conditions":"Cool (10–20°C), very wet. Most destructive potato disease in highlands.","scouting_method":"Scout every 3–4 days in cool wet weather. Check lower leaves first.","treatments":[{"type":"chemical","product":"Metalaxyl + Mancozeb (Ridomil Gold MZ 68 WG)","rate":"2.5 kg/ha","timing":"Apply preventatively every 7–10 days when cool and wet."},{"type":"chemical","product":"Propamocarb + Fenamidone (Consento 450 SC)","rate":"2 L/ha","timing":"Rotate with Ridomil to manage resistance."}],"prevention":["Certified blight-free seed potatoes","Resistant varieties","Avoid overhead irrigation"]},
  {"id":"DIS_024","common_name":"Potato common scab","scientific_name":"Streptomyces scabies","pathogen_type":"bacterial","affects":["CROP_021"],"symptoms":["Rough corky raised or sunken lesions on tuber surface","Brown scab patches on skin","Affects marketability — not flesh quality"],"severity":"medium","favourable_conditions":"Alkaline soils (pH >7.0), dry conditions during tuber initiation.","scouting_method":"Inspect tubers at harvest.","treatments":[{"type":"cultural","product":"Maintain soil pH 5.0–6.0","rate":"N/A","timing":"Correct pH before planting."}],"prevention":["Maintain pH below 6.0","Adequate irrigation during tuber initiation","Crop rotation 3 years"]},
  {"id":"DIS_025","common_name":"Papaya ring spot virus","scientific_name":"Papaya ringspot virus (PRSV)","pathogen_type":"viral","affects":["CROP_022"],"symptoms":["Yellow mosaic on leaves","Distorted shoe-string leaves in severe cases","Concentric ring spots on fruit skin","Stunted growth"],"severity":"critical","favourable_conditions":"Spread by aphids. Worse near wild cucurbit hosts.","scouting_method":"Inspect fruit surface for ring spots. Monitor aphid populations.","treatments":[{"type":"cultural","product":"Remove infected plants immediately","rate":"N/A","timing":"As soon as ring spots confirmed."}],"prevention":["Plant away from cucurbit crops","PRSV-resistant varieties","Mineral oil sprays reduce transmission"]},
  {"id":"DIS_026","common_name":"Mango anthracnose","scientific_name":"Colletotrichum gloeosporioides","pathogen_type":"fungal","affects":["CROP_023"],"symptoms":["Dark sunken lesions on fruit — from latent pre-harvest infection","Black water-soaked lesions on flowers","Irregular dark spots on young leaves","Post-harvest fruit rot"],"severity":"high","favourable_conditions":"High humidity, rain during flowering. Infection is latent.","scouting_method":"Monitor during flowering. Check fruit at harvest for sunken lesions.","treatments":[{"type":"chemical","product":"Propiconazole (Tilt 250 EC)","rate":"500 mL/100 L water","timing":"Apply at 50% flowering and again at fruit set."}],"prevention":["Hot water treatment of fruit (52°C for 5 min)","Good orchard hygiene","Adequate spacing"]},
  {"id":"DIS_027","common_name":"Avocado Phytophthora root rot","scientific_name":"Phytophthora cinnamomi","pathogen_type":"fungal","affects":["CROP_024"],"symptoms":["Wilting and dieback of branches","Small pale leaves — nutrient deficiency symptoms","Dead blackened feeder roots","Gradual tree decline and death over 1–3 seasons"],"severity":"critical","favourable_conditions":"Waterlogged heavy soils. pH >7.0. Poor drainage.","scouting_method":"Dig beside declining trees. Check feeder roots — healthy=white, diseased=black.","treatments":[{"type":"chemical","product":"Phosphonate (Fosphite) trunk injection","rate":"20 mL/tree by trunk injection","timing":"Apply 2× per year — before summer rains and after.","notes":"Stimulates plant defence — does not kill Phytophthora directly."}],"prevention":["Plant only in well-drained soils","Avoid waterlogging","Use resistant rootstocks (Duke 7, Dusa)"]},
  {"id":"DIS_028","common_name":"Panama disease (Fusarium wilt)","scientific_name":"Fusarium oxysporum f.sp. cubense","pathogen_type":"fungal","affects":["CROP_025"],"symptoms":["Yellowing of older leaves from outside in","Leaves collapse hanging down pseudostem","Internal reddish-brown discolouration when pseudostem cut","Plant death — no recovery"],"severity":"critical","favourable_conditions":"Soil-borne. Spreads through infested soil, water, tools. Persists 30+ years.","scouting_method":"Check for yellowing older leaves. Cut pseudostem at base — red-brown staining confirms Fusarium.","treatments":[{"type":"cultural","product":"No effective chemical cure","rate":"N/A","timing":"Remove and destroy infected plants. Disinfect tools."}],"prevention":["Cavendish or resistant varieties","Certified disease-free nurseries only","Never move soil from affected areas"]},
  {"id":"DIS_029","common_name":"Sugarcane smut","scientific_name":"Sporisorium scitamineum","pathogen_type":"fungal","affects":["CROP_026"],"symptoms":["Long black whip-like structure from growing point","Premature emergence of side shoots","Stunted tillers with poor cane formation"],"severity":"high","favourable_conditions":"Dry conditions following drought. Wind-spread spores.","scouting_method":"Walk field and count whips. More than 1% smutted stools = serious.","treatments":[{"type":"chemical","product":"Hot-water treatment of setts (50°C for 2 hours)","rate":"N/A","timing":"Before planting.","notes":"Kills systemic infection in planting material."}],"prevention":["Smut-resistant varieties","Remove and destroy whips before spore release","Certified clean planting material"]},
  {"id":"DIS_030","common_name":"Sesame phyllody","scientific_name":"Sesame phytoplasma","pathogen_type":"viral","affects":["CROP_027"],"symptoms":["Flowers transformed into leaf-like structures (phyllody)","Stunted growth and greening of petals","No capsule formation on affected branches"],"severity":"medium","favourable_conditions":"Spread by leafhoppers. Worse in late-planted crops.","scouting_method":"Inspect flowers from flowering stage. Green leaf-like flowers confirm phyllody.","treatments":[{"type":"cultural","product":"Remove infected plants","rate":"N/A","timing":"As soon as symptoms appear."}],"prevention":["Control leafhopper vectors","Early planting"]},
  {"id":"DIS_031","common_name":"Pumpkin powdery mildew","scientific_name":"Erysiphe cichoracearum","pathogen_type":"fungal","affects":["CROP_028"],"symptoms":["White powdery patches on both leaf surfaces","Rapid spread in dry warm conditions","Early leaf senescence and reduced fruit fill"],"severity":"medium","favourable_conditions":"Warm dry conditions (20–28°C). Common in late season.","scouting_method":"Check leaf surfaces from 4 weeks after transplanting.","treatments":[{"type":"chemical","product":"Wettable sulphur (Thiovit Jet 80 WG)","rate":"3 kg/ha","timing":"Apply at first sign. Repeat every 10 days."}],"prevention":["Resistant varieties","Adequate plant spacing"]},
  {"id":"DIS_032","common_name":"Garlic white rot","scientific_name":"Sclerotium cepivorum","pathogen_type":"fungal","affects":["CROP_029"],"symptoms":["Yellowing and death of leaves from tips downward","White cottony mycelium at bulb base","Small black sclerotia (2 mm) on rotted bulb","Soft rotted bulbs at harvest"],"severity":"critical","favourable_conditions":"Cool soils (10–20°C). Soil-borne — sclerotia survive 20+ years.","scouting_method":"Pull suspect plants. Examine bulb base for white mycelium and black sclerotia.","treatments":[{"type":"chemical","product":"Tebuconazole (Folicur 250 EW) soil drench","rate":"1 L/ha","timing":"Apply at planting in known infested fields."}],"prevention":["Do not plant alliums in fields with white rot history","Disease-free planting material","No crop rotation breaks the cycle"]},
  {"id":"DIS_033","common_name":"Pepper Phytophthora blight","scientific_name":"Phytophthora capsici","pathogen_type":"fungal","affects":["CROP_030"],"symptoms":["Water-soaked lesions on stem at soil level — rapid girdling","Plant wilts suddenly and collapses (crown rot)","Water-soaked rotten fruit","White sporulation on infected tissue in wet conditions"],"severity":"critical","favourable_conditions":"Waterlogged soils, heavy rainfall, warm (25–30°C).","scouting_method":"Check base of plants for water-soaked lesions after heavy rain. Sudden wilting is diagnostic.","treatments":[{"type":"chemical","product":"Metalaxyl + Mancozeb (Ridomil Gold MZ) soil drench","rate":"3 kg/ha","timing":"Apply as soil drench at transplanting and after heavy rain."}],"prevention":["Raised beds for excellent drainage","Avoid waterlogging","Crop rotation minimum 3 years"]},


    # ── New diseases for extended crops ──────────────────────────────────────

  {"id":"DIS_034","common_name":"Coffee leaf rust","scientific_name":"Hemileia vastatrix","pathogen_type":"fungal",
   "affects":["CROP_050"],
   "symptoms":["Yellow-orange powdery spots on lower leaf surface","Corresponding pale spots on upper surface","Severe defoliation — bare stems by season end","Reduced yield and plant vigour over years"],
   "severity":"critical","favourable_conditions":"High humidity (>80%), temperatures 16–28°C, free water on leaves.",
   "scouting_method":"Check undersides of 10 leaves from 10 plants per 0.5 ha. Assess % leaf area affected. Monitor humidity levels.",
   "treatments":[
     {"type":"chemical","product":"Copper hydroxide (Kocide 2000)","rate":"2.5 kg/ha in 600 L water","timing":"Protective — begin before conditions favour infection. Repeat every 21 days."},
     {"type":"chemical","product":"Propiconazole (Tilt 250 EC)","rate":"500 mL/ha","timing":"At first sign. Systemic — gives 4–6 weeks control."}],
   "prevention":["Plant resistant varieties (Catimor, Sarchimor)","Maintain adequate shade","Avoid over-cropping","Remove and destroy infected leaves"]},

  {"id":"DIS_035","common_name":"Leaf spot of coriander","scientific_name":"Alternaria petroselini","pathogen_type":"fungal",
   "affects":["CROP_060"],
   "symptoms":["Small brown spots with yellow halo on leaves","Spots enlarge and coalesce — extensive leaf blight","Premature defoliation","Stem cankers in severe cases"],
   "severity":"medium","favourable_conditions":"Wet foliage, cool temperatures 15–25°C, high humidity.",
   "scouting_method":"Check 20 plants per bed for leaf spots. Assess severity. Look for wet weather correlation.",
   "treatments":[
     {"type":"chemical","product":"Mancozeb + Copper (Dithane M-45 tank mix)","rate":"2 kg/ha","timing":"At first spot, repeat every 10–14 days."},
     {"type":"organic","product":"Copper oxychloride","rate":"1.5 kg/ha in 200 L water","timing":"Protective, spray after rain."}],
   "prevention":["Avoid overhead irrigation — use drip","Good air circulation — correct spacing","Use certified disease-free seed","Remove crop debris"]},

  {"id":"DIS_036","common_name":"Root rot of okra","scientific_name":"Pythium spp. / Rhizoctonia solani","pathogen_type":"fungal",
   "affects":["CROP_036"],
   "symptoms":["Seedling damping off — collapse at soil level","Yellowing of lower leaves","Wilting despite adequate soil moisture","Brown to black discolouration of roots"],
   "severity":"high","favourable_conditions":"Waterlogged soil, poor drainage, temperatures 25–30°C.",
   "scouting_method":"Check emerging seedlings daily for damping off. Pull wilting plants — check root colour. Observe drainage patterns across the plot.",
   "treatments":[
     {"type":"chemical","product":"Ridomil Gold (Metalaxyl 4% + Mancozeb 64%)","rate":"1 kg/100 L water — soil drench","timing":"At transplanting and early growth stages."}],
   "prevention":["Well-drained beds — raised if soil heavy","Avoid overwatering","Rotate with cereals for 2+ seasons","Treat seed with fungicide before planting"]},

  {"id":"DIS_037","common_name":"Banana bunchy top virus","scientific_name":"Banana bunchy top virus (BBTV)","pathogen_type":"viral",
   "affects":["CROP_025"],
   "symptoms":["Leaves short, narrow, and erect — bunched appearance at top","Leaf edges turn yellow then brown","Dark green streaks on leaf midrib and petiole","No flower or fruit production — plant dies"],
   "severity":"critical","favourable_conditions":"Spread by banana aphid (Pentalonia nigronervosa). Warm temperatures 20–30°C.",
   "scouting_method":"Walk the entire plantation monthly. Look for stunted bunchy appearance. No bunchy top plant ever recovers — remove immediately.",
   "treatments":[
     {"type":"chemical","product":"Imidacloprid (Confidor) for aphid vector control","rate":"150 mL/ha","timing":"Apply when aphids detected. Controls spread not the virus."}],
   "prevention":["Use certified virus-free planting material","Rogue and destroy infected plants immediately — do not leave in field","Control aphid populations rigorously","Do not move plant material from infected areas"]},

  {"id":"DIS_038","common_name":"Fusarium wilt of sweet potato","scientific_name":"Fusarium oxysporum f.sp. batatas","pathogen_type":"fungal",
   "affects":["CROP_019"],
   "symptoms":["Yellowing of lower leaves progressing upward","Vascular discolouration — brown staining in stem cross-section","Plant wilts progressively and dies","Roots shrunken and discoloured"],
   "severity":"high","favourable_conditions":"Infected soil, wounds at planting, warm soil (25–30°C), poor drainage.",
   "scouting_method":"Check plants showing early wilt — cross-section stem near base. Brown vascular tissue is diagnostic. Map affected areas.",
   "treatments":[
     {"type":"chemical","product":"No effective chemical cure once established — focus on prevention","rate":"N/A","timing":"N/A"}],
   "prevention":["Use clean, disease-free vine cuttings only","Rotate with cereals or legumes for 3+ years","Avoid soil compaction and waterlogging","Plant resistant varieties where available"]},

]

PEST_BY_ID    = {p["id"]: p for p in PESTS}
DISEASE_BY_ID = {d["id"]: d for d in DISEASES}

PESTS_BY_CROP: dict = {}
for _p in PESTS:
    for _cid in _p["affects"]:
        PESTS_BY_CROP.setdefault(_cid, []).append(_p)

DISEASES_BY_CROP: dict = {}
for _d in DISEASES:
    for _cid in _d["affects"]:
        DISEASES_BY_CROP.setdefault(_cid, []).append(_d)